// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'chatroom_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

ChatRoomEntity _$ChatRoomEntityFromJson(Map<String, dynamic> json) =>
    ChatRoomEntity(
      access: json['access'] as bool?,
      answerText: json['answer_text'] as String?,
      answersCount: (json['answers_count'] as num?)?.toInt(),
      attachmentCount: (json['attachment_count'] as num?)?.toInt(),
      attachments: json['attachments'] as List<dynamic>?,
      attachmentsUploaded: json['attachments_uploaded'] as bool?,
      attendingCount: (json['attending_count'] as num?)?.toInt(),
      attendingStatus: json['attending_status'] as bool?,
      audioCount: (json['audio_count'] as num?)?.toInt(),
      audios: json['audios'] as List<dynamic>?,
      autoFollowDone: json['auto_follow_done'] as bool?,
      cardCreationTime: json['card_creation_time'] as String?,
      communityId: (json['community_id'] as num?)?.toInt(),
      communityName: json['community_name'] as String?,
      createdAt: json['created_at'],
      date: json['date'] as String?,
      dateEpoch: (json['date_epoch'] as num?)?.toInt(),
      chatroomImageUrl: json['chatroom_image_url'] as String?,
      lastConversationId: (json['last_conversation_id'] as num?)?.toInt(),
      dateTime: (json['date_time'] as num?)?.toInt(),
      unseenCount: (json['unseen_count'] as num?)?.toInt(),
      duration: (json['duration'] as num?)?.toInt(),
      followStatus: json['follow_status'] as bool?,
      hasEventRecording: json['has_event_recording'] as bool?,
      header: json['header'] as String,
      id: (json['id'] as num).toInt(),
      imageCount: (json['image_count'] as num?)?.toInt(),
      images: json['images'] as List<dynamic>?,
      includeMembersLater: json['include_members_later'] as bool?,
      isEdited: json['is_edited'] as bool?,
      isGuest: json['is_guest'] as bool?,
      isPaid: json['is_paid'] as bool?,
      isPending: json['is_pending'] as bool?,
      isPrivate: json['is_private'] as bool?,
      isPrivateMember: json['is_private_member'] as bool?,
      isSecret: json['is_secret'] as bool?,
      isTagged: json['is_tagged'] as bool?,
      member: json['member'] == null
          ? null
          : UserEntity.fromJson(
              json['member'] as Map<String, dynamic>),
      topic: json['topic'] == null
          ? null
          : ConversationEntity.fromJson(json['topic'] as Map<String, dynamic>),
      muteStatus: json['mute_status'] as bool?,
      onlineLinkEnableBefore:
          (json['online_link_enable_before'] as num?)?.toInt(),
      onlineLinkType: json['online_link_type'],
      pdf: json['pdf'] as List<dynamic>?,
      pdfCount: (json['pdf_count'] as num?)?.toInt(),
      pollsCount: (json['polls_count'] as num?)?.toInt(),
      reactions: json['reactions'] as List<dynamic>?,
      secretChatroomLeft: json['secret_chatroom_left'] as bool?,
      shareLink: json['share_link'] as String?,
      state: (json['state'] as num?)?.toInt(),
      title: json['title'] as String,
      type: (json['type'] as num?)?.toInt(),
      videoCount: (json['video_count'] as num?)?.toInt(),
      videos: json['videos'] as List<dynamic>?,
      participantCount: (json['participants_count'] as num?)?.toInt(),
      totalResponseCount: (json['total_response_count'] as num?)?.toInt(),
      isPinned: json['is_pinned'] as bool?,
      externalSeen: json['external_seen'] as bool?,
      chatRequestState: (json['chat_request_state'] as num?)?.toInt(),
      chatRequestedBy: json['chat_requested_by'] == null
          ? null
          : UserEntity.fromJson(
              json['chat_requested_by'] as Map<String, dynamic>),
      chatRequestedById: (json['chat_requested_by_id'] as num?)?.toInt(),
      chatroomWithUser: json['chatroom_with_user'] == null
          ? null
          : UserEntity.fromJson(
              json['chatroom_with_user'] as Map<String, dynamic>),
      chatroomWithUserId: (json['chatroom_with_user_id'] as num?)?.toInt(),
      lastResponseMembers: (json['last_response_members'] as List<dynamic>?)
          ?.map((e) => UserEntity.fromJson(e as Map<String, dynamic>))
          .toList(),
      memberCanMessage: json['member_can_message'] as bool?,
      userId: (json['user_id'] as num?)?.toInt(),
    );

Map<String, dynamic> _$ChatRoomEntityToJson(ChatRoomEntity instance) =>
    <String, dynamic>{
      'access': instance.access,
      'answer_text': instance.answerText,
      'answers_count': instance.answersCount,
      'attachment_count': instance.attachmentCount,
      'attachments': instance.attachments,
      'attachments_uploaded': instance.attachmentsUploaded,
      'attending_count': instance.attendingCount,
      'attending_status': instance.attendingStatus,
      'audio_count': instance.audioCount,
      'audios': instance.audios,
      'auto_follow_done': instance.autoFollowDone,
      'card_creation_time': instance.cardCreationTime,
      'chatroom_image_url': instance.chatroomImageUrl,
      'last_conversation_id': instance.lastConversationId,
      'unseen_count': instance.unseenCount,
      'community_id': instance.communityId,
      'community_name': instance.communityName,
      'created_at': instance.createdAt,
      'date': instance.date,
      'date_epoch': instance.dateEpoch,
      'date_time': instance.dateTime,
      'duration': instance.duration,
      'follow_status': instance.followStatus,
      'has_event_recording': instance.hasEventRecording,
      'header': instance.header,
      'id': instance.id,
      'image_count': instance.imageCount,
      'images': instance.images,
      'include_members_later': instance.includeMembersLater,
      'is_edited': instance.isEdited,
      'is_guest': instance.isGuest,
      'is_paid': instance.isPaid,
      'is_pending': instance.isPending,
      'is_private': instance.isPrivate,
      'is_private_member': instance.isPrivateMember,
      'is_secret': instance.isSecret,
      'is_tagged': instance.isTagged,
      'member': instance.member,
      'topic': instance.topic,
      'mute_status': instance.muteStatus,
      'online_link_enable_before': instance.onlineLinkEnableBefore,
      'online_link_type': instance.onlineLinkType,
      'pdf': instance.pdf,
      'pdf_count': instance.pdfCount,
      'polls_count': instance.pollsCount,
      'reactions': instance.reactions,
      'secret_chatroom_left': instance.secretChatroomLeft,
      'share_link': instance.shareLink,
      'state': instance.state,
      'title': instance.title,
      'type': instance.type,
      'video_count': instance.videoCount,
      'videos': instance.videos,
      'participant_count': instance.participantCount,
      'total_response_count': instance.totalResponseCount,
      'is_pinned': instance.isPinned,
      'external_seen': instance.externalSeen,
      'member_can_message': instance.memberCanMessage,
      'chat_request_state': instance.chatRequestState,
      'chat_requested_by': instance.chatRequestedBy,
      'chat_requested_by_id': instance.chatRequestedById,
      'chatroom_with_user': instance.chatroomWithUser,
      'chatroom_with_user_id': instance.chatroomWithUserId,
      'user_id': instance.userId,
      'last_response_members': instance.lastResponseMembers,
    };
