name: likeminds_chat_fl
description: Likeminds flutter chat SDK
version: 1.5.2
homepage: "https://likeminds.community/"

environment:
  sdk: ">=2.18.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  get_it: ^7.2.0
  envied: ^0.3.0
  dio: ^5.1.2
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1
  curl_logger_dio_interceptor: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  hive_generator:
  envied_generator:

false_secrets:
  - /*.json
